"""Self-service printer installers.

Windows cannot discover a CUPS queue — it speaks WS-Discovery, CUPS speaks DNS-SD, and no
daemon bridges the two for printers. Every documented alternative asks the user for an
elevated shell and three commands, which in practice means a walk to their desk.

So the server hands out an installer tailored to the queue, and the user runs one line.
The script self-elevates through UAC rather than requiring the user to find an admin
console first.

Deliberately unauthenticated: it contains no secrets, only the server address and queue
name that every client needs anyway, and requiring a login to install a printer defeats
the purpose. It is generated from the queue record, never from user input, so a caller
cannot inject arbitrary content into a script other people will run elevated.
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, Request, status
from fastapi.responses import PlainTextResponse
from sqlalchemy.orm import Session

from ..db import session_scope
from ..models import PrinterQueue
from . import cups_control

router = APIRouter(tags=["install"], include_in_schema=False)


def _server_host(request: Request) -> str:
    """The address the client used to reach us — which is by definition routable for them."""
    host = request.headers.get("host", "")
    return host.split(":")[0] if host else (request.url.hostname or "localhost")


def _cups_port() -> int:
    """CUPS is on 631 with host networking, 6631 with the default bridge."""
    import os

    server = os.environ.get("CUPS_SERVER", "")
    if ":" in server:
        try:
            return int(server.rsplit(":", 1)[1])
        except ValueError:
            pass
    return 631


def _load_queue(session: Session, queue: str) -> PrinterQueue:
    row = session.get(PrinterQueue, queue)
    if row is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "no such printer")
    return row


@router.get("/install/windows/{queue}.ps1", response_class=PlainTextResponse)
def windows_installer(queue: str, request: Request) -> str:
    # Validating against the same rules used to create queues keeps anything unexpected
    # out of a script that will run with administrator rights.
    try:
        cups_control.validate_name(queue)
    except cups_control.CupsControlError as exc:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, str(exc)) from exc

    with session_scope() as session:
        row = _load_queue(session, queue)
        display = row.description or row.location or "Inspected printer"
        device_ip = ""
        if row.device_uri:
            try:
                device_ip, _port = cups_control.device_endpoint(row.device_uri)
            except cups_control.CupsControlError:
                device_ip = ""

    host = _server_host(request)
    port = _cups_port()
    uri = f"http://{host}:{port}/printers/{queue}"
    self_url = f"http://{host}:{request.url.port or 8088}/install/windows/{queue}.ps1"
    friendly = queue.replace("-", " ").title()

    # Removing a direct port is only meaningful if we know the device address.
    bypass_cleanup = ""
    if device_ip:
        bypass_cleanup = f'''
# Remove any port that prints straight to the device. Those bypass inspection entirely,
# and Windows will happily prefer one if it exists.
foreach ($p in @(Get-PrinterPort | Where-Object {{
        $_.PrinterHostAddress -eq "{device_ip}" -or $_.Name -like "*{device_ip}*" }})) {{
    foreach ($pr in @(Get-Printer | Where-Object {{ $_.PortName -eq $p.Name }})) {{
        Write-Host "  removing '$($pr.Name)' - it printed directly to the printer" -ForegroundColor Yellow
        Remove-Printer -Name $pr.Name -ErrorAction SilentlyContinue
    }}
    Remove-PrinterPort -Name $p.Name -ErrorAction SilentlyContinue
}}
'''

    return f'''# janus-print - installs "{friendly}" ({display})
# Generated by {host}. Everything printed through this queue is inspected before it
# reaches the printer.

$ErrorActionPreference = "Stop"
$uri  = "{uri}"
$name = "{friendly}"

# Re-launch elevated if needed, so the user does not have to find an admin console.
$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
if (-not ([Security.Principal.WindowsPrincipal]$identity).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)) {{
    Write-Host "Requesting administrator rights..." -ForegroundColor Cyan
    Start-Process powershell -Verb RunAs -ArgumentList @(
        "-NoProfile", "-ExecutionPolicy", "Bypass", "-NoExit",
        "-Command", "irm {self_url} | iex"
    )
    return
}}

Write-Host "Installing $name" -ForegroundColor Cyan
Write-Host "  via $uri"

# IPP printing is an optional Windows feature and is off on many images. Without it the
# IPP class driver does not exist and the install fails with an unrelated-looking error.
$feature = Get-WindowsOptionalFeature -Online `
    -FeatureName "Printing-Foundation-InternetPrinting-Client" -ErrorAction SilentlyContinue
if ($feature -and $feature.State -ne "Enabled") {{
    Write-Host "  enabling Internet Printing Client..." -ForegroundColor Cyan
    Enable-WindowsOptionalFeature -Online `
        -FeatureName "Printing-Foundation-InternetPrinting-Client" -NoRestart -All | Out-Null
}}

$driver = "Microsoft IPP Class Driver"
if (-not (Get-PrinterDriver -Name $driver -ErrorAction SilentlyContinue)) {{
    try {{ Add-PrinterDriver -Name $driver -ErrorAction Stop }}
    catch {{ $driver = "Microsoft PS Class Driver"; Add-PrinterDriver -Name $driver -ErrorAction SilentlyContinue }}
}}

if (-not (Get-PrinterPort -Name $uri -ErrorAction SilentlyContinue)) {{
    try {{
        Add-PrinterPort -Name $uri -ErrorAction Stop
    }} catch {{
        # Some builds refuse to create an internet port this way; printui always works.
        Write-Host "  using printui fallback..." -ForegroundColor Yellow
        rundll32 printui.dll,PrintUIEntry /if /b "$name" /f "$env:windir\\inf\\ntprint.inf" /r "$uri" /m "$driver"
    }}
}}

$existing = Get-Printer -Name $name -ErrorAction SilentlyContinue
if ($existing) {{
    if ($existing.PortName -ne $uri) {{ Set-Printer -Name $name -PortName $uri }}
}} elseif (Get-PrinterPort -Name $uri -ErrorAction SilentlyContinue) {{
    Add-Printer -Name $name -DriverName $driver -PortName $uri
}}
{bypass_cleanup}
$installed = Get-Printer -Name $name -ErrorAction SilentlyContinue
if ($installed -and $installed.PortName -eq $uri) {{
    Write-Host ""
    Write-Host "  Done. '$name' is installed and inspected." -ForegroundColor Green
    Write-Host "  Print to it exactly as normal." -ForegroundColor Green
}} else {{
    Write-Host ""
    Write-Host "  Install did not complete. If the Internet Printing Client feature was" -ForegroundColor Red
    Write-Host "  just enabled, reboot and run this again." -ForegroundColor Red
}}
'''


@router.get("/install/unix/{queue}.sh", response_class=PlainTextResponse)
def unix_installer(queue: str, request: Request) -> str:
    """macOS/Linux equivalent, for clients that cannot see the Bonjour advert."""
    try:
        cups_control.validate_name(queue)
    except cups_control.CupsControlError as exc:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, str(exc)) from exc

    with session_scope() as session:
        _load_queue(session, queue)

    host = _server_host(request)
    port = _cups_port()

    return f'''#!/bin/sh
# janus-print - installs the inspected queue "{queue}".
# Everything printed through it is inspected before reaching the printer.
set -e

URI="ipp://{host}:{port}/printers/{queue}"
NAME="{queue}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Re-running with sudo..."
  exec sudo "$0" "$@"
fi

echo "Installing ${{NAME}} via ${{URI}}"
lpadmin -p "${{NAME}}" -E -v "${{URI}}" -m everywhere
cupsenable "${{NAME}}"
cupsaccept "${{NAME}}"
echo "Done. '${{NAME}}' is installed and inspected."
'''
